services:
  netfora-api:
    container_name: netfora-api
    image: netfora-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: NetFora.Api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NetForaDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=true;Encrypt=false
      - JwtSettings__SecretKey=ThisIsAVeryLongSecretKeyForDevelopmentPurposesOnly123!
      - JwtSettings__Issuer=NetForaApi
      - JwtSettings__Audience=NetForaClient
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Debug
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - netfora-network

  netfora-processor:
    container_name: netfora-processor
    image: netfora-processor
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: NetFora.EventProcessor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=NetForaDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=true
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - netfora-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: netfora-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./InitialCreate.sql:/docker-entrypoint-initdb.d/InitialCreate.sql:ro
    networks:
      - netfora-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrongPassword123!", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  netfora-network:
    driver: bridge

volumes:
  sqlserver_data: